1 start
Surtt/nextjs-course pull request #2
Opened 2023-08-01 11:49 UTC by Surtt

Привет! 

Настраивал проект по этой статье:
https://dev.to/nausaf/set-up-linting-and-formatting-for-code-and-scss-files-in-a-nextjs-project-43fb

Кода стараюсь закоммитить файлы или запускаю команду `next lint` получаю ошибки вида:
<img width="1139" alt="Снимок экрана 2023-08-01 в 14 07 59" src="https://github.com/Surtt/nextjs-course/assets/29383368/573f9686-b342-4a71-952f-f244b82805e6">
<img width="1144" alt="Снимок экрана 2023-08-01 в 14 08 14" src="https://github.com/Surtt/nextjs-course/assets/29383368/d437e20d-dc1d-473b-a7a6-b8f65f7db1d4">

Как их пофиксить? И не совсем понимаю, при чем тут промисы

2023-08-05 10:18 UTC, Grinv requested changes

2023-08-05 10:18 UTC, Grinv commented on .eslintrc.js
> +  // rules: {
Не оставляй мусор и лишние комментарии)

2023-08-05 10:18 UTC, Grinv commented on app/globals.css
> +
А зачем тут пустые строки?

2023-08-05 10:18 UTC, Grinv commented on app/layout.tsx
> +      <body className={openSans.className}>{children}</body>
Я вообще за то, чтоб задавать шрифт, как переменную и потом прописывать её в globals.css в body. Мало ли где потом может понадобиться
Пример как сделать: https://nextjs.org/docs/app/api-reference/components/font#css-variables

2023-08-05 10:18 UTC, Grinv commented on app/page.module.css
> +
Зачем тут везде пустые строки?)

2023-08-05 10:18 UTC, Grinv commented on app/page.module.css
> +@media (hover: hover) and (pointer: fine) {
👍

2023-08-05 10:18 UTC, Grinv commented on components/button/button.tsx
> +export const Button = ({
Вообще мне удобнее и нагряднее писать, как
```javascript
export const Button: FC<ButtonProps> = ({ anyProps }} => {
   // ...
}
```
Так читать удобнее, потому что типы не пересекаются с входящими пропсами. Но это имхо)

2023-08-05 10:18 UTC, Grinv commented on components/button/button.module.css
> +  margin-left: 10px;
Проще сделать через навешивание на кнопку `dispay: flex` и `gap: 10px`
Если будет 1 элемент внутри кнопки - расстояние не применится
Если 2 и более - расстояние применится автоматически
Тогда стрелке не понадобятся стили и обёртка из span

2023-08-05 10:18 UTC, Grinv commented on components/button/button.tsx
> +            [styles.right]: arrow === 'right',
Если ты делаешь общий компонент button, а не специфическую кнопку, то предлагаю использовать более общие название. Мы в кнопку можем передать не только arrow, но и вообще любую иконку. Поэтому советую переименовать `arrow` -> `icon`
И потестить с разными передаваемыми иконками, которые могут быть любого размера и вида. И пропиши стили так, что не зависимости от передаваемой иконки, кнопка всегда выглядела бы одинаково :)

2023-08-05 10:18 UTC, Grinv commented on components/button/button.tsx
> +          <ArrowIcon />
Учитывая, что компонент button общий и универсальный, я бы передавал иконку, как пропс, а не прописывал её тут.
Если кнопка специфичная, то лучше переименовать её по-другому, чтоб никого не смущать)

2023-08-05 10:18 UTC, Grinv commented on components/card/card.module.css
> +  row-gap: 16px;
Можно просто gap. Postcss за тебя всё сделает)

2023-08-05 10:18 UTC, Grinv commented on components/card/card.tsx
> +      <img src='https://placehold.co/330x200' alt='placeholder' />
Давай использовать компонент `next/image`. Он не просто так создавался)

2023-08-05 10:18 UTC, Grinv commented on components/card/card.tsx
> +    <div className={cn(styles.card)}>
Для всяких карточек применять тэг `article`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article
>Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.

2023-08-05 10:18 UTC, Grinv commented on components/like/like.module.css
> +  column-gap: 2px;
Тоже можно просто gap

2023-08-05 10:18 UTC, Grinv commented on components/title/title.tsx
> +      return <h1 className={styles.h1}>{children}</h1>;
В дальнейшем может получиться так, что тебе надо будет накидывать доп. стили. Обычно я это учитываю у себя в проектах и прокидываю возможность применения кастомного класса
```javascript
return <h1 className={cn(styles.h1, className)}>{children}</h1>;
```
но опять же, возможно тебе это и не понадобится. Но это стоит учитывать)

2023-08-05 10:18 UTC, Grinv commented on components/typography/typography.module.css
> +  margin: 0;
Хм. Вообще лучше для таких вещей применять какой-нибудь normalizer типа
https://github.com/necolas/normalize.css
или
https://github.com/sindresorhus/modern-normalize
и прописывать первым в globals.css

2023-08-05 10:18 UTC, Grinv commented on components/like/like.svg
лучше всякие иконки, картинки, файлы кидать в `/public`
`/public/icons`
`/public/images`
`/public/pdf`

2023-08-05 10:18 UTC, Grinv commented on components/typography/typography.tsx
> +export const Typography = ({
По поводу typescript ошибки - я вообще не понял, откуда она у тебя появлятся)
Я к себе склонировал проект и ошибки не вижу. Да и у тебя нигде не применяется `getTypeAtLocation`
Попробуй сделать https://tinytip.co/tips/vscode-restart-ts/
И напиши, актуально ли ещё

2023-08-05 10:49 UTC, Grinv requested changes

2023-08-05 10:49 UTC, Grinv commented on components/card/card.tsx
> +    <div className={cn(styles.card)}>
Зачем тут cn?

2023-08-05 10:49 UTC, Grinv commented on components/card/card.tsx
> +export const Card = ({}: CardProps) => {
Если у тебя компонент ничего не принимает, то зачем типы?)
Я понимаю, что в будущем появятся, но сейчас то их нет

2023-08-05 17:15 UTC, Surtt commented on app/globals.css
> +
> А зачем тут пустые строки?

@Grinv Так это stylelint так форматирует

2023-08-05 17:17 UTC, Surtt commented on app/page.module.css
> +
> Зачем тут везде пустые строки?)

@Grinv stylelint)

2023-08-05 17:30 UTC, Surtt commented on components/button/button.tsx
> +export const Button = ({
> Вообще мне удобнее и нагряднее писать, как
> 
> ```js
> export const Button: FC<ButtonProps> = ({ anyProps }} => {
>    // ...
> }
> ```
> 
> Так читать удобнее, потому что типы не пересекаются с входящими пропсами. Но это имхо)

@Grinv Насколько я знаю, использование данного подхода нежелательно.
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components

2023-08-05 17:35 UTC, Surtt commented on components/card/card.module.css
> +  row-gap: 16px;
> Можно просто gap. Postcss за тебя всё сделает)

Так мне же в данном случае именно gap нужен именно для строк? Просто gap добавит мне отступы и по столбцам, разве нет?)

2023-08-05 17:56 UTC, Surtt commented on components/typography/typography.tsx
> +export const Typography = ({
> По поводу typescript ошибки - я вообще не понял, откуда она у тебя появлятся) Я к себе склонировал проект и ошибки не вижу. Да и у тебя нигде не применяется `getTypeAtLocation` Попробуй сделать https://tinytip.co/tips/vscode-restart-ts/ И напиши, актуально ли ещё

@Grinv Ты не видишь ошибки, потому что я удалил **eslintCommand** в **lint-staged.config.js**) Без этого я бы не смог запушить) Попробуй добавить **eslintCommand** в **lint-staged.config.js** и закоммитить или выполнить команду ```next lint```
На всякий случай дублирую ссылку: https://dev.to/nausaf/set-up-linting-and-formatting-for-code-and-scss-files-in-a-nextjs-project-43fb

2023-08-05 17:56 UTC, Surtt commented on components/card/card.tsx
> +    <div className={cn(styles.card)}>
Согласен, тут не нужен

2023-08-07 18:44 UTC, Surtt commented on app/layout.tsx
> +      <body className={openSans.className}>{children}</body>
@Grinv Если я задаю шрифт таким образом и пытаюсь прописать в global.css, в таком случае переменная не обнаружена
<img width="703" alt="Снимок экрана 2023-08-07 в 21 41 44" src="https://github.com/Surtt/nextjs-course/assets/29383368/cd07012d-e7c6-4679-8439-96be780d67f8">

2023-08-10 10:55 UTC, Grinv requested changes

2023-08-10 10:55 UTC, Grinv commented on app/layout.tsx
> +      <body className={openSans.className}>{children}</body>
А как ты её прописываешь в 'next/font/google'?

2023-08-10 10:55 UTC, Grinv commented on components/button/button.tsx
> +export const Button = ({
Я хотел акцентировать внимание не на `anyProps`, а на типизации `FC`. AnyProps для краткости, что всё не расписывать. Не получилось)) Мой косяк, напишу полностью, что я имел ввиду:
```javascript
export const Button: FC<ButtonProps> = ({
  variant,
  arrow = 'none',
  children,
  className,
  ...props
}) => {
```
так мы не мешаем параметры с типами, типизация как бы стоит немного обособленно. Как по мне, так проще читать.

2023-08-10 10:55 UTC, Grinv commented on components/card/card.module.css
> +  row-gap: 16px;
А у тебя разве есть отступы по столбцам? По коду вроде нет)
Если появятся - уберём конечно, либо зададим кастомный)

2023-08-10 10:55 UTC, Grinv commented on components/typography/typography.tsx
> +export const Typography = ({
Хорошо, попозже попробую

2023-08-10 17:21 UTC, Surtt commented on app/layout.tsx
> +      <body className={openSans.className}>{children}</body>
> А как ты её прописываешь в 'next/font/google'?

@Grinv да, именно так

2023-08-10 17:28 UTC, Surtt commented on components/button/button.tsx
> +export const Button = ({
@Grinv Я думаю, я понял тебя сразу) Ты имеешь ввиду именно таким образом типизировать компонент `export const Button: FC<ButtonProps>` а не `export const Button = ({}: ButtonProps) => {}` ? Если так, то вот по ссылке которую я оставил выше, приводятся причины, почему не стоит использовать данный подход)

2023-08-10 17:32 UTC, Surtt commented on components/card/card.module.css
> +  row-gap: 16px;
> А у тебя разве есть отступы по столбцам? По коду вроде нет) Если появятся - уберём конечно, либо зададим кастомный)

@Grinv просто gap в данном случае тоже работает да, но row-gap мне кажется в данной ситуации более очевиден, из кода сразу понятно где gap именно используется. то есть выглядит более релевантным что ли) Тут наверное дело в предпочтении)

2023-08-11 08:41 UTC, Grinv approved these changes

2023-08-11 08:41 UTC, merged