2 components
Surtt/nextjs-course pull request #3
Opened 2023-08-07 19:48 UTC by Surtt

2023-08-10 18:08 UTC, Grinv requested changes

2023-08-10 18:08 UTC, Grinv commented on app/globals.css
> +}
Не надо засорять globals нормалайзом копипастом)
Спокойно поставь себе как зависимость какой-нибудь normalize.css или modern-normalize. Заимпорти в _app или css. А вот если чего-то не будет хватать - то можешь дописать уже в global.css.

А ещё лучше создать какой-нибудь файл preflight.css. В него заимпортить modern-normalize + дописать глобальные резетеры, которых не хватает.
И уже этот preflight.css заимпортить в globals.css
Тогда и globals.css будет чище и ты будешь знать, что правила нормалайзы у тебя лежат в одном месте, а не разбросаны :)

2023-08-10 18:08 UTC, Grinv commented on app/globals.css
> +  max-width: 100vw;
Хм. Не припомню случая, чтоб body нужен был < 100vw
Так что можно спокойно писать `width: 100vw;`

2023-08-10 18:08 UTC, Grinv commented on app/globals.css
> +  font-family: Open-sans, sans-serif;
`font-family: var(--font-open-sans)` не срабатывает?

2023-08-10 18:08 UTC, Grinv commented on app/layout.tsx
> +  children: React.ReactNode;
Опять же, рекомендую внутри объявления функции не миксовать типы и данные. Сложно читать. Лучше выше опиши интерфейс и тут его заимплементь. Даже если там один параметр передаваемый всего)

2023-08-10 18:08 UTC, Grinv commented on app/layout.tsx
> +            src='./icons/github.svg'
В данном случае можно просто '/icons/github.svg'
Но не надо путь к картинкам описывать через относительный путь, всегда делай картинки через абсолютный)
То что сразу все картинки в public складываешь - молодец
Но вообще рекомендую заимпортить иконку как объект и уже прокинуть в Image. Так кеширование лучше работает. И настрой себе алиас для public тоже :)

```javascript
import githubIcon from '@/icons/github.svg';
<Image src={githubIcon} />

2023-08-10 18:08 UTC, Grinv commented on app/page.module.css
> +@media (width < 1206px) {
Если у тебя в голове уже сложились какие-то брейкпойнты, я бы рекомендовал их все сложить в css переменные в одно место и везде использовать их :)

2023-08-10 18:08 UTC, Grinv commented on components/button/button.tsx
> +      {iconPosition !== 'none' && iconPosition === 'right' && icon}
зачем тебе none и двойная проверка? Пусть приходит undefined, ты и так это обработаешь)
```javascript
{iconPosition === 'left' && icon}
{children}
{iconPosition === 'right' && icon}

2023-08-10 18:08 UTC, Grinv commented on components/card/card.tsx
> +      <div className={cn(styles.top)}>
cn не нужен

2023-08-10 18:08 UTC, Grinv commented on components/card/card.tsx
> +      <div className={cn(styles.middle)}>
cn не нужен)

2023-08-10 18:08 UTC, Grinv commented on components/card/card.tsx
> +      <div className={cn(styles.bottom)}>
Можно так сильно не беспокоиться о безопасности. Если вместо класса придёт undefined, react его не отрисует

2023-08-10 18:08 UTC, Grinv commented on components/card/card.tsx
> +        <Button variant='text' icon={<ArrowIcon />} iconPosition='right'>
Вот, Вот так с иконкой гораздо лучше👍

2023-08-10 18:08 UTC, Grinv commented on components/header/header.tsx
> +      <p className={styles.logo}>.my_blog</p>
Ну это точно не `p` :)
p - это некий абзац, законченное предложение

2023-08-10 18:08 UTC, Grinv commented on components/like/like.tsx
> +      onClick={() => setIsLike(true)}
Хитро)) Мы т.е. можем только залайкать, а вернуть состояние обратно в нелайкнутое уже не можем?))
Тут надо toggle применять. Причём учти, что у тебя запрос ещё идёт, это занимает какое-то время

2023-08-10 18:08 UTC, Grinv commented on components/typography/typography.tsx
> +      {...props}
Ставь спрэды первыми, не забывай, я уже писал об этом. Когда-нибудь так перезапишешь свойство и будешь потом долго дебажить. Я в своей жизни пару раз так обжёгся, теперь всегда помню)
```javascript
<p {...props} className={classes}>

2023-08-11 06:36 UTC, Surtt commented on app/globals.css
> +  font-family: Open-sans, sans-serif;
> font-family: var(--font-open-sans)

@Grinv не срабатывает

Я подключаю шрифты таким образом:
```
import { Open_Sans } from 'next/font/google';

const openSans = Open_Sans({
  weight: ['300', '400', '700'],
  subsets: ['cyrillic', 'latin'],
  variable: '--font-open-sans',
});
```

Потом использую переменную в global.css и выдает ошибку `Cannot resolve '--font-open-sans' custom property `

2023-08-11 18:34 UTC, Surtt commented on app/page.module.css
> +@media (width < 1206px) {
@Grinv Можешь привести, пожалуйста, пример, не совсем понимаю, как я тут могу использовать переменные

2023-08-11 18:34 UTC, Surtt commented on app/page.module.css
> +@media (width < 1206px) {
@Grinv Можешь привести, пожалуйста, пример, не совсем понимаю, как я тут могу использовать переменные

2023-08-24 17:42 UTC, merged